### ISSUE TITLE
bug with loguru 5 

### ISSUE THREAD

**Issue by dtrckd** [dtrckd/pymake#5]
I got this 

```
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.7/site-packages/loguru/_handler.py", line 107, in emit
    dynamic_format = self._formatter(record)
  File "/home/admin/.local/lib/python3.7/site-packages/pymake/core/logformatter.py", line 32, in format
    level = record['level'].lower()
AttributeError: 'RecordLevel' object has no attribute 'lower'`
```
with loguru==0.5.1

works with  loguru==0.3.2
